### ISSUE TITLE
name typo correction - volunteers on tables and field

### ISSUE THREAD

**Issue by bltMustafa** [acikkaynak/musahit-harita-backend#16]
v3 of DB Schema

Changes:
* volunteers typo fixes
* priority field added to volunteer_counts table

![gonullu harita db schema - v3](https://github.com/acikkaynak/musahit-harita-backend/assets/6787068/5055a072-3965-4391-99ae-58635a40050a)

**Comment by salihdev0** [comment]
Can you pass enum values for source type? We need this in the init.sql command. @bltMustafa

**Comment by salihdev0** [comment]
and I request the following name changes in the sources table:

```
old | new
adi => name,
tip => type
```

**Comment by salihdev0** [comment]
merged in #15
